### ISSUE TITLE
Issues migrating to v21

### ISSUE THREAD

**Issue by Steven-Thelin** [commercetools/merchant-center-application-kit#2840]
**Describe the issue**

When following the migration guidelines and expanding custom-application-config with the new fields, I’m getting an error while running the application locally, to specifically not include the new fields.

```
Error: .env should NOT have additional properties: development at validateConfig 
```
```
Error: .env should NOT have additional properties: applicationId at validateConfig 
```
The above is conflicting with the statement in the [migration docs](https://docs.commercetools.com/custom-applications/migrating-from-project-level-custom-applications), at [Update the Custom Application config](https://docs.commercetools.com/custom-applications/migrating-from-project-level-custom-applications#update-the-custom-application-config).

If I remove the required keys in question, I get a different error:
```
[BABEL] #PATH#/CommerceTools Custom Applications/order-management/src/index.js: The 'autoLabel' option must be undefined, or one of the following: "dev-only", "never", "always" (While processing: "#PATH#/CommerceTools Custom Applications/order-management/node_modules/@emotion/babel-preset-css-prop/dist/emotion-babel-preset-css-prop.cjs.js$2")
```

**To Reproduce**

1. Follow the migration guide, to update from v19 to v21.

**Expected behavior**

For the application to run

**Additional context**

Additional info:
`@comercetools-frontend/*`: `21.16.0`
`@commercetools-uikit/`: `^12.0.0`
Operating System: MacOS 12.0 Monterey

**Comment by CarlosCortizasCT** [comment]
Hello @Steven-Thelin 

Thanks for reaching out regarding the problems you're facing when migrating a Custom Application.

I guess we would need a little more extra information for us to find out what might be the problem. So, could you?:
* Provide the list of all dependencies in your package.json
* Provide the list of scripts in your package.json
* Provide which package manager are you using (npm, yarn,...)
* If you have a custom webpack configuration, provide it too.
* Make sure the `app-kit` and `ui-kit` dependencies in your `node_modules` have been updated

Thanks.

**Comment by Steven-Thelin** [comment]
Hi @CarlosCortizasCT !

Thank's for your response. Sure thing, here comes.

**Dependencies**
```
"dependencies": {
    "@apollo/client": "^3.7.0",
    "@commercetools-frontend/actions-global": "21.16.0",
    "@commercetools-frontend/application-components": "21.16.0",
    "@commercetools-frontend/application-shell": "21.16.0",
    "@commercetools-frontend/assets": "21.16.0",
    "@commercetools-frontend/i18n": "21.16.0",
    "@commercetools-frontend/mc-html-template": "21.16.0",
    "@commercetools-frontend/permissions": "21.16.0",
    "@commercetools-uikit/async-select-field": "^12.0.0",
    "@commercetools-uikit/async-select-input": "^12.0.0",
    "@commercetools-uikit/avatar": "^12.0.0",
    "@commercetools-uikit/card": "^12.0.0",
    "@commercetools-uikit/checkbox-input": "^12.0.0",
    "@commercetools-uikit/collapsible-panel": "^12.0.0",
    "@commercetools-uikit/creatable-select-field": "^12.0.0",
    "@commercetools-uikit/creatable-select-input": "^12.0.0",
    "@commercetools-uikit/data-table": "^12.0.0",
    "@commercetools-uikit/data-table-manager": "^12.0.0",
    "@commercetools-uikit/date-range-field": "^12.0.0",
    "@commercetools-uikit/flat-button": "^12.0.0",
    "@commercetools-uikit/grid": "^12.0.0",
    "@commercetools-uikit/icons": "^12.0.0",
    "@commercetools-uikit/loading-spinner": "^12.0.0",
    "@commercetools-uikit/multiline-text-field": "^12.0.0",
    "@commercetools-uikit/number-input": "^12.0.0",
    "@commercetools-uikit/pagination": "^12.0.0",
    "@commercetools-uikit/primary-action-dropdown": "^12.0.0",
    "@commercetools-uikit/select-field": "^12.0.0",
    "@commercetools-uikit/select-input": "^12.0.0",
    "@commercetools-uikit/spacings": "^12.0.0",
    "@commercetools-uikit/spacings-stack": "^12.0.0",
    "@commercetools-uikit/stamp": "^12.0.0",
    "@commercetools-uikit/text": "^12.0.0",
    "@commercetools-uikit/text-field": "^12.0.0",
    "@commercetools-uikit/text-input": "^12.0.0",
    "@commercetools-uikit/time-input": "^12.0.0",
    "@commercetools-uikit/toggle-input": "^12.0.0",
    "@commercetools-uikit/tooltip": "^12.0.0",
    "@formatjs/cli": "^2.11.2",
    "axios": "^0.21.0",
    "bulk-update-versions": "1.1.0",
    "cross-env": "^7.0.3",
    "formik": "^2.1.5",
    "lodash": "^4.17.20",
    "moment": "^2.29.0",
    "prop-types": "15.7.2",
    "react": "17.0.0",
    "react-dom": "17.0.0",
    "react-intl": "^5.8.1",
    "react-redux": "7.2.1",
    "react-router-dom": "5.2.0",
    "redux": "4.0.5",
    "shx": "^0.3.3"
  },
  "devDependencies": {
    "@commercetools-frontend/jest-preset-mc-app": "17.0.0",
    "@commercetools-frontend/mc-scripts": "17.0.0",
    "@testing-library/react": "^12.0.0",
    "dotenv-cli": "3.2.0",
    "enzyme": "3.11.0",
    "fast-memoize": "^2.5.2",
    "jest": "26.4.0"
  }
  ```
  
  **Scripts**
  ```
  "scripts": {
    "build": "set URL_ENV=https://mc.europe-west1.gcp.commercetools.com/lakrids-by-blow/ && set CDN_URL_ENV=https://lakrids-custom-app-production-service.azurewebsites.net/order-management && mc-scripts build",
    "azure-production": "shx rm -rf public/ && set URL_ENV=https://mc.europe-west1.gcp.commercetools.com/lakrids-by-blow/ && set CDN_URL_ENV=https://lakrids-custom-app-production-service.azurewebsites.net/order-management && mc-scripts build production --scripts-prepend-node-path && npm run azure-compile && shx cp -r public public_production",
    "azure-staging": "shx rm -rf public/ && set URL_ENV=https://mc.europe-west1.gcp.commercetools.com/lakrids-by-blow-staging/ && set CDN_URL_ENV=https://lakrids-app-ordermanagement-staging.azurewebsites.net/order-management && mc-scripts build --scripts-prepend-node-path && npm run azure-compile && shx cp -r public public_staging",
    "start": "set URL_ENV=https://mc.europe-west1.gcp.commercetools.com/lakrids-by-blow/ && set CDN_URL_ENV=https://lakrids-custom-app-production-service.azurewebsites.net/order-management && dotenv -- mc-scripts start",
    "compile-html:local": "NODE_ENV=production MC_APP_ENV=development dotenv -- mc-scripts compile-html --transformer @commercetools-frontend/mc-dev-authentication/transformer-local.js",
    "start:prod:local": "yarn compile-html:local && mc-scripts serve",
    "extract-intl": "formatjs extract --format=$(pwd)/intl-formatter.js --out-file=$(pwd)/src/i18n/data/core.json 'src/**/!(*.spec).js'",
    "test": "jest --config jest.test.config.js",
    "test:watch": "jest --config jest.test.config.js --watch",
    "update-versions": "bulk-update-versions --match '^@commercetools-frontend/(?!ui-kit)(.*)'",
    "compile-html": "mc-scripts compile-html --use-local-assets",
    "azure-compile": "mc-scripts compile-html --use-local-assets --scripts-prepend-node-path"
  },
  ```
  
  **Package manager**
  Npm (nvm for versioning)
  
  No custom webpack and all app-kit and ui-kit deps seem up-to-date 🙂

**Comment by CarlosCortizasCT** [comment]
Hi @Steven-Thelin,

You would also need to update these dependencies too:
![image](https://user-images.githubusercontent.com/97907068/193781387-81fb9c8d-6aaf-4e82-8ab7-47ec0bdec95c.png)

You would update both to (at least) version `21.6.0` you're using for the other `app-kit` dependencies.

**Comment by Steven-Thelin** [comment]
@CarlosCortizasCT Thanks, that did the trick! I don't know how i skipped that. However I run into another issue now:

```
Error:  must have required property 'icon' at validateConfig (/Users/steventhelin/Development/E-Commerce/lakrids-commercetools/CommerceTools Custom Applications/order-management/node_modules/@commercetools-frontend/mc-scripts/node_modules/@commercetools-frontend/application-config/dist/commercetools-frontend-application-config.cjs.dev.js:529:11)
```

```
{
  "icon": "WorldIcon",
  "key": "order-management",
  "mainMenuLink": {
    "uriPath": "order-management",
    "permissions": ["ViewProducts"],
    "featureToggle": null,
    "submenu": [],
    "labelAllLocales": [
      {
        "locale": "en",
        "value": "Orders"
      },
      {
        "locale": "de",
        "value": "Orders"
      },
      {
        "locale": "es",
        "value": "Orders"
      }
    ]
  }
}
```

Did i format something wrong? I'm aware that the icon format isn't according to the docs, but the error seems more concise about the property not being set 🙂 

Also the docs "convert" from
```
"icon": "HeartIcon",
```
to
```
"icon": "${path:@commercetools-frontend/assets/application-icons/rocket.svg}",
```

**Comment by CarlosCortizasCT** [comment]
Hello @Steven-Thelin, 

Technically, the `icon` property validation only checks it exists and that it is a string.
You are expected to follow the [new format](https://docs.commercetools.com/custom-applications/api-reference/application-config#icon) to select the icon you want to use, as you already noticed.

We would like to know what's the complete filename of your configuration file? Is it `custom-application-config.json`? Is the content you provided complete or is it just an excerpt of your config file?

Thanks.

**Comment by Steven-Thelin** [comment]
@CarlosCortizasCT The complete config file is the following (removed sensitive content), as `custom-application-config.json`:
```
{
  "name": "Commerce Management",
  "entryPointUriPath": "order-management",
  "cloudIdentifier": "gcp-eu",
  "oAuthScopes": [],
  "env": {
    "development": {
      "initialProjectKey": "lakrids-by-bulow"
    },
    "production": {
      "applicationId": "",
      "url": "${env:URL_ENV}",
      "cdnUrl": "${env:CDN_URL_ENV}"
    }
  },
  "headers": {
    "csp": {
      "connect-src": [
        "source 1",
        "source 2",
        "localhost:5000"
      ]
    }
  },
  "additionalEnv": {
    "authorizationHeader": "authorization header content"
  }
}
```

However, we cannot find the `applicationId` anywhere.
The menu contents is within a file named `menu.json`:
```
{
  "icon": "WorldIcon",
  "key": "order-management",
  "mainMenuLink": {
    "uriPath": "order-management",
    "permissions": ["ViewProducts"],
    "featureToggle": null,
    "submenu": [],
    "labelAllLocales": [
      {
        "locale": "en",
        "value": "Orders"
      },
      {
        "locale": "de",
        "value": "Orders"
      },
      {
        "locale": "es",
        "value": "Orders"
      }
    ]
  }
}
```

**Comment by CarlosCortizasCT** [comment]
Hello @Steven-Thelin 

All the configuration must be included in the `custom-application-config.json`.
The `menu.json` is not used anymore so you should move its contents to the main config file (the `key` property is not needed).

Regarding the `applicationId`, you can find this value in the Merchant Center once you configured your Custom Application ([here](https://docs.commercetools.com/custom-applications/api-reference/application-config#envproductionapplicationid) you can find the docs about it).

**Comment by emmenko** [comment]
You also need to specify the auth requirements in the `oAuthScopes` field.

Could you also share what the `authorizationHeader` is for?

**Comment by CarlosCortizasCT** [comment]
Hello @Steven-Thelin 

Regarding the `oAuthScopes`, it depends on the resources your Custom Application might need to access or manipulate.
For instance, if your Custom Application would only read products information, this could be enough:
```
"oAuthScopes": {
    "view": ["view_products"],
    "manage": []
}
```

If your Custom Application will only need to create or update products, you would use something like this:
```
"oAuthScopes": {
    "view": [],
    "manage": ["manage_products"]
}
```
(_`manage` scopes implicit grant `view` permissions_).

[Here are the docs](https://docs.commercetools.com/custom-applications/api-reference/application-config#oauthscopes) about configuring this field in the Custom Application configuration file.

Hope this helps.

**Comment by Steven-Thelin** [comment]
Hello again.

I created the Custom App in Merchant Center, assigned the correct ApplicationId and permissions, as well as put the Custom App into its ready state; however when launching the app locally i still get the error: "Not enough permissions to access this resource".

```
"oAuthScopes": {
    "view": ["view_customers"],
    "manage": ["manage_orders"]
  },
```

The same has been set for the Custom App in MC.
Any ideas?

**Comment by Steven-Thelin** [comment]
@CarlosCortizasCT I managed to get past the permission error (Was in the menu apparently). However, now I get what looks like a 404 instead 😓 

> We could not find what you are looking for
> The item you are looking for may have been deleted, does not exist, or the URL was entered incorrectly. Check the URL and try again.
>
> Please contact your system administrator or the commercetools Help Desk if you have any further questions.

**Comment by Steven-Thelin** [comment]
Update: Nope, still the permissions error.

**Comment by emmenko** [comment]
@Steven-Thelin Hi 👋

How are you evaluating the permissions in the MC? For example in routes (see docs https://docs.commercetools.com/custom-applications/development/permissions#in-routes).

The error does not seem to be coming from the `<ApplicationShell>`, so I assume you are rendering a `<MaintenancePageLayout>` somewhere in your code?

Can you check or maybe share with us the `routes.js` content?

Also, you have been mentioning the usage of `ViewProducts` permission. This is not possible to use anymore, as Custom Applications now have their own permission pairs. See https://docs.commercetools.com/custom-applications/migrating-from-project-level-custom-applications#migrate-user-permissions.

In case it helps, I would also recommend looking at the [starter template](https://github.com/commercetools/merchant-center-application-kit/tree/main/application-templates/starter) implementation, in particular around the usage of permissions and how to apply them.

**Comment by Steven-Thelin** [comment]
Hello @emmenko 👋🏻 Thank you for your answer.

## A
> The error does not seem to be coming from the <ApplicationShell>, so I assume you are rendering a <MaintenancePageLayout> somewhere in your code?

Your assumption is correct, we use `MaintenancePageLayout` (I don't know if it's correct to do so).

## B
I also tried updating another one of our custom apps to v21, and interestingly encountered the same permissions error. But after specifying a `.x` version difference in the `permissions` package, it worked. However that application is now stuck on the following error, after updating packages to v19:
```
TypeError: message.split is not a function
    at formatMessage (/Users/steventhelin/Development/E-Commerce/lakrids-commercetools/CommerceTools Custom Applications/shipping-zone-management/node_modules/react-dev-utils/formatWebpackMessages.js:18:23)
```

## C
Contents of `route.js`
```
import React from 'react';
import PropTypes from 'prop-types';
import { Route, Switch } from 'react-router-dom';
import { useIsAuthorized } from '@commercetools-frontend/permissions';
import LockedDiamondSVG from '@commercetools-frontend/assets/images/locked-diamond.svg';
import { MaintenancePageLayout } from '@commercetools-frontend/application-components';
import MainView from './components/main-view';
import { PERMISSIONS } from './constants';

const PageUnauthorized = () => (
  <MaintenancePageLayout
    imageSrc={LockedDiamondSVG}
    title="Not enough permissions to access this resource"
    paragraph1="We recommend to contact your project administrators for further questions."
  />
);

const ApplicationRoutes = ({ match }) => {
  const canViewProducts = useIsAuthorized({
    demandedPermissions: [PERMISSIONS.ViewProducts],
  });
  if (!canViewProducts) {
    return <PageUnauthorized />;
  }
  return (
    <Switch>
      <Route
        path={`${match.path}/some-other-route`}
        render={() => <div>{'Nothing to see'}</div>}
      />
      <Route render={(routerProps) => <MainView match={routerProps.match} />} />
    </Switch>
  );
};
ApplicationRoutes.displayName = 'ApplicationRoutes';
ApplicationRoutes.propTypes = {
  match: PropTypes.shape({
    path: PropTypes.string,
    params: PropTypes.shape({
      projectKey: PropTypes.string.isRequired,
    }).isRequired,
  }).isRequired,
};

export default ApplicationRoutes;
```

**Comment by Steven-Thelin** [comment]
@emmenko Hi again!

Updating the routes file (contents provided down below) i get a different error:
![Screenshot 2022-10-11 at 11 42 55](https://user-images.githubusercontent.com/19597055/195056356-bbb1fe43-6f93-45a5-9976-4627fdee554e.png)


```
import React from 'react';
import PropTypes from 'prop-types';
import { Route, Switch } from 'react-router-dom';
import { useIsAuthorized } from '@commercetools-frontend/permissions';
import LockedDiamondSVG from '@commercetools-frontend/assets/images/locked-diamond.svg';
import { MaintenancePageLayout } from '@commercetools-frontend/application-components';
import MainView from './components/main-view';
import { PERMISSIONS } from './constants';

const PageUnauthorized = () => (
  <MaintenancePageLayout
    imageSrc={LockedDiamondSVG}
    title="Not enough permissions to access this resource"
    paragraph1="We recommend to contact your project administrators for further questions."
  />
);

const ApplicationRoutes = ({ match }) => {
  const canViewProducts = useIsAuthorized({
    demandedPermissions: [PERMISSIONS.View],
  });
  const canManage = useIsAuthorized({
    demandedPermissions: [PERMISSIONS.Manage],
  });

  if (!canViewProducts || !canManage) {
    return <PageUnauthorized />;
  }
  return (
    <Switch>
      <Route
        path={`${match.path}/some-other-route`}
        render={() => <div>{'Nothing to see'}</div>}
      />
      <Route render={(routerProps) => <MainView match={routerProps.match} />} />
    </Switch>
  );
};
ApplicationRoutes.displayName = 'ApplicationRoutes';
ApplicationRoutes.propTypes = {
  match: PropTypes.shape({
    path: PropTypes.string,
    params: PropTypes.shape({
      projectKey: PropTypes.string.isRequired,
    }).isRequired,
  }).isRequired,
};

export default ApplicationRoutes;
```

**Comment by emmenko** [comment]
```
  const canViewProducts = useIsAuthorized({
    demandedPermissions: [PERMISSIONS.ViewProducts],
  });
  if (!canViewProducts) {
    return <PageUnauthorized />;
  }
```

So as I mentioned, this is the issue. Please read the migration docs: https://docs.commercetools.com/custom-applications/migrating-from-project-level-custom-applications#migrate-user-permissions

You also don't need to check for the "view" permission in the routes anymore, as this is done implicitly by the `<ApplicationShell>`.

I would strongly recommend to look at the [starter template](https://github.com/commercetools/merchant-center-application-kit/tree/main/application-templates/starter) implementation, in particular to:
* the `entry-point.jsx`
* the `routes.jsx`

and compare them with your application, as I assume there are a bunch of things that you don't need anymore.

For instance, your `routes.js` can be simplified to this (as it seems you only have one route?):

```js
const ApplicationRoutes = () => <MainView />
```

Note that the `routerProps` and `match` don't need to be passed around as props anymore, you can use the hook `useRouteMatch`.

**Comment by emmenko** [comment]
> Updating the routes file (contents provided down below) i get a different error:

What is the error? Can you check the console in devtools?

**Comment by Steven-Thelin** [comment]
@emmenko Thank you for your answers! I'll dig into it and come back with the results 🙂 👏🏻 
The error i provided (the screenshot of a top-down ice-cream) isn't present anymore, now it's just stuck on a loader. But I'll try your provided resources before trying to address that 👏🏻 

Thanks again

**Comment by Steven-Thelin** [comment]
@emmenko Hi again,

This leads to a different error:
```
/Users/steventhelin/Development/E-Commerce/lakrids-commercetools/CommerceTools Custom Applications/order-management/node_modules/@commercetools-frontend/application-config/dist/formatters-7e163a9c.cjs.dev.js:55
  .split('_') // Uppercase the first character of each word split.
   ^

TypeError: Cannot read property 'split' of undefined
    at formatEntryPointUriPathToResourceAccessKey
```

This doesn't seem to be a part of our application code?

**Comment by Steven-Thelin** [comment]
@emmenko So far so good! I'm past the permissions error and I just _briefly_ see the page as it should be. However after about 1 second I get a red banner saying
> Insufficient scope. One of the following scopes is missing: view_project_settings.

The console contains the following errors:
> [SENTRY]: Error: Unmapped error
    at commercetools-frontend-react-notifications.esm.js:394:1

**Comment by emmenko** [comment]
The error should be pretty clear: the OAuth Scope `view_project_settings` is missing in the Custom Application config `oAuthScopes` field.

You need to list there all OAuth Scopes required to access the related APIs used by your Custom Application.

Read more about it here: https://docs.commercetools.com/custom-applications/concepts/oauth-scopes-and-user-permissions

**Comment by Steven-Thelin** [comment]
Works! Thanks a lot for the help, @emmenko  😄 
This has definitely helped me towards finalising the migration process for the rest of our applications as well.

Thanks once again 😊

**Comment by Steven-Thelin** [comment]
@emmenko Definitely! The last missing piece was primarily the (described very clear in the error message) lacking permissions. It's very helpful that it shows which permissions are actually missing, as I had no clue which permissions we needed for this application. Furthermore the other issues were related to the overall setup, specifically the app-config and general structure of the application. So I did like you proposed and compared our setup to the starter kit, then to refactor all the "main" files to match.

But maybe a relation to the version-relative starter kit could be attached to the migration guides, to ensure old code-bases follow the "up to date" equivalent 😊

**Comment by Steven-Thelin** [comment]
Hi @emmenko 

Upon browsing the application I encountered this error:
```
Insufficient scope. One of the following scopes is missing: view_types.
```

I tried adding `view_types` to the auth scope, however upon doing that I cannot sign into the application (a regular login error asking me to check my email and/or password). I encountered the same thing prior to that error, with another error saying `missing: manage_my_orders`. However i fixed that by adding `manage_orders` instead. Where can i check the validity of the suggested missing auth strings, for example `view_types`?
